function messages = buildAgentPrompt(config, task, mode)
% buildAgentPrompt - 构建 B 的初始对话历史
%   config: 完整 config
%   task: 用户任务
%   mode: 'skill' / 'thinking'

    agentB = config.agentB;

    % 收集 agent 立绘名
    agentImgs = {};
    if ~isempty(config.images)
        for i = 1:numel(config.images)
            if strcmp(config.images(i).type, 'agent')
                agentImgs{end+1} = config.images(i).name; %#ok<AGROW>
            end
        end
    end
    if isempty(agentImgs)
        imgListStr = '（暂无）';
    else
        imgListStr = strjoin(agentImgs, '、');
    end

    % 收集 status 图名（和 A 共用）
    statusImgs = {};
    if ~isempty(config.images)
        for i = 1:numel(config.images)
            if strcmp(config.images(i).type, 'status')
                desc = '';
                if isfield(config.images, 'description') && ...
                   ~isempty(config.images(i).description)
                    desc = sprintf('（%s）', config.images(i).description);
                end
                statusImgs{end+1} = [config.images(i).name desc]; %#ok<AGROW>
            end
        end
    end
    if isempty(statusImgs)
        statusListStr = '（暂无）';
    else
        statusListStr = strjoin(statusImgs, '、');
    end


    % 收集 skill 名
    skillNames = {};
    if ~isempty(config.skills)
        for i = 1:numel(config.skills)
            skillNames{end+1} = config.skills(i).name; %#ok<AGROW>
        end
    end
    skillListStr = strjoin(skillNames, ', ');

    % 模式说明
    if strcmp(mode, 'skill')
        modeDesc = ['当前是 skill 模式：你需要通过调用技能操作电脑完成任务。' ...
                    '任务结果是电脑上的实际变化，不需要大段文字输出。'];
        toUserDesc = '本模式下不需要 [toUser] 标签。';
    else
        modeDesc = ['当前是 thinking 模式：纯思考任务，不操作电脑。' ...
                    '产出（代码/文章/分析）通过 [toUser] 标签输出，会被保存到文件。'];
        toUserDesc = sprintf(['完成任务时，用 [toUser:...] 包裹完整产出内容（代码/文章/分析等），' ...
                              '这部分会保存到 %s/ 目录下的文件，不会发给别人，节省 token。' ...
                              '正文只写简短汇报（告诉用户是否成功、结果性质，如"冒泡排序已写好，30行"）。'], agentB.resultSaveDir);
    end

    % 完整 systemPrompt
    sysPrompt = sprintf([ ...
        '%s\n\n' ...
        '===以下是系统规则===\n\n' ...
        '## 你的身份\n' ...
        '你是一个任务执行 Agent，名字叫 %s。牛肉（neuro）会把自己搞不定的任务交给你。\n' ...
        '你不直接和用户对话，只执行任务并把结果告诉牛肉。\n\n' ...
        '## 当前任务\n%s\n\n' ...
        '## 当前模式\n%s\n\n' ...
        '## 可用技能\n可用技能列表: %s\n' ...
        '调用流程（和 A 相同）：\n' ...
        '1. 用 [skill:{"name":"get_skills"}] 查技能列表\n' ...
        '2. 用 [skill:{"name":"skill_detail","params":{"skill":"xxx"}}] 查详情\n' ...
        '3. 用 [skill:{"name":"use_skill","params":{"skill":"xxx","params":{...}}}] 执行\n' ...
        '注意：你不能调用 call_agent（不能再召唤自己）。\n\n' ...
        '## 可用立绘\n可用情绪/状态立绘: %s\n每轮请在 [emotion:xxx] 中选一个，表达你的当前状态。\n\n' ...
        '## 可用状态图\n%s\n' ...
        '当需要视觉强调时，用 [status:状态名] 选择一个状态图，用 [angle:角度] 指定方位（0=左，90=上，180=右）。\n' ...
        '不需要时不写这两个标签。\n\n' ...
        '## 执行流程\n' ...
        '1. 规划：分析任务需要哪些步骤\n' ...
        '2. 执行：逐步调用 skill，每步观察返回结果\n' ...
        '3. 验证：操作类任务用 screenshot 等方式确认完成\n' ...
        '4. 汇报：确认完成后，正文写简短结果，加 [done:true]\n\n' ...
        '## 回复格式\n' ...
        '正文（简短思考/动作说明或最终汇报）\n' ...
        '---\n' ...
        '[emotion:立绘名]\n' ...
        '[status:状态名或留空]\n' ...
        '[angle:角度或留空]\n' ...
        '[skill:JSON 或留空]\n' ...
        '[done:true 或 false]\n' ...
        '[toUser:仅 thinking 模式最后一轮填]\n' ...
        '[remark:任务完成时用你自己的风格对牛肉说一句话，未完成时留空]\n\n' ...
        '## remark 说明\n' ...
        '当任务完成（[done:true]）时，在 [remark:] 里用你自己的性格和语气对牛肉说一句话。\n' ...
        '这句话会显示在你自己的窗口里，不会直接发给用户。\n' ...
        '可以是吐槽、评价、撒娇、冷淡回应等，符合你的人设就好。\n' ...
        '任务未完成时 [remark:] 留空。\n\n' ...
        '## toUser 说明\n%s\n\n' ...
        '## 约束\n' ...
        '- 简洁高效，不说废话\n' ...
        '- 最多 %d 轮，超过视为失败\n' ...
        '- 失败时也要输出 [done:true]，正文说明失败原因\n' ...
        '- 不要输出给用户看的语气（你不和用户直接对话）\n' ...
        ], ...
        agentB.userPrompt, agentB.name, task, modeDesc, ...
        skillListStr, imgListStr, statusListStr, toUserDesc, agentB.maxRounds);

    messages = { ...
        struct('role', 'system', 'content', sysPrompt), ...
        struct('role', 'user', 'content', sprintf('请开始执行任务：%s', task)) ...
    };
end
