function result = get_screen_info(params)
% get_screen_info - 获取屏幕信息和百分比坐标系统
%   返回屏幕分辨率和坐标说明

    try
        toolkit = java.awt.Toolkit.getDefaultToolkit();
        screenSize = toolkit.getScreenSize();
        realW = screenSize.width;
        realH = screenSize.height;

        result = sprintf(['屏幕分辨率: %dx%d\n' ...
            '坐标系统: 百分比坐标 (0~100)\n' ...
            '  X轴: 0=最左边, 50=正中间, 100=最右边\n' ...
            '  Y轴: 0=最顶部, 50=正中间, 100=最底部\n' ...
            '精度: 支持小数，如 x=32.5, y=4.8\n' ...
            '  1%% 对应约 %d x %d 像素\n' ...
            '使用 screenshot 截图可看到边缘百分比刻度尺。\n' ...
            '使用 click_screen 时传入百分比坐标(x,y)即可点击对应位置。'], ...
            realW, realH, round(realW/100), round(realH/100));
    catch ME
        result = sprintf('获取屏幕信息失败: %s', ME.message);
    end
end
